{% set name = "sphinx-multiversion" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-multiversion-{{ version }}.tar.gz
  sha256: 5cd1ca9ecb5eed63cb8d6ce5e9c438ca13af4fa98e7eb6f376be541dd4990bcb

build:
  entry_points:
    - sphinx-multiversion=sphinx_multiversion:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sphinx >=2.1

test:
  imports:
    - sphinx_multiversion
  commands:
    - pip check
    - sphinx-multiversion --help
  requires:
    - pip

about:
  home: https://holzhaus.github.io/sphinx-multiversion/
  summary: Add support for multiple versions to sphinx
  license: BSD-2-Clause
  license_file: LICENSE
  dev_url: https://github.com/Holzhaus/sphinx-multiversion
  doc_url: https://holzhaus.github.io/sphinx-multiversion

extra:
  recipe-maintainers:
    - xylar
